language: minimal
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  # global:
  # - DOCKER_COMPOSE_VERSION=1.4.2
  matrix:
  # legacy
  - FOLDER="fpm-alpine" 
    TAG="16-$FOLDER" 
  
  - FOLDER="fpm"
    TAG="16-$FOLDER"
    ADD_TAG="latest"




install:
# Add docker-retag executable
- wget -q https://github.com/joshdk/docker-retag/releases/download/0.0.2/docker-retag && chmod +x docker-retag
# Add env variables for docker-retag
- export DOCKER_USER=$DOCKER_USERNAME
- export DOCKER_PASS=$DOCKER_PASSWORD

before_script:
# Login to hub.docker.com
- echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
# Pull Kaniko image
- docker pull gcr.io/kaniko-project/executor:latest
# Clone official nextcloud/docker repo
- git clone https://github.com/nextcloud/docker.git
# change git content
- cd docker; git checkout $TAG


script:
# Build Image via kaniko
- docker run
    -v "$TRAVIS_BUILD_DIR/docker/.examples/dockerfiles/full/$FOLDER":/workspace
    -v $HOME/.docker:/kaniko/.docker
    gcr.io/kaniko-project/executor:latest
      --context=/workspace
      --verbosity=info
      --destination=$DOCKER_SLUG/nextcloud-full:$TAG

# Retag images for other tags
- for i in $ADD_TAG;
  do
    ../docker-retag $DOCKER_SLUG/nextcloud-full:$TAG $i;
  done

